AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: secureiac-logs
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Enabled  # Enable versioning for the LoggingBucket
      LoggingConfiguration:
        DestinationBucketName: !Ref SecureIACBucket  # Enable logging to the SecureIACBucket
        LogFilePrefix: "logs/"

  SecureIACBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: secureiac
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: "logs/"
      VersioningConfiguration:
        Status: Enabled  # Versioning enabled for SecureIACBucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

Outputs:
  SecureIACBucketName:
    Description: "Name of the secure S3 bucket"
    Value: !Ref SecureIACBucket

  LoggingBucketName:
    Description: "Name of the logging S3 bucket"
    Value: !Ref LoggingBucket
