Resources:
  SecureIACBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: secureiac  
      VersioningConfiguration:
        Status: Enabled  # This enables versioning on the S3 bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true  # Blocks public ACLs
        IgnorePublicAcls: true  # Ignores public ACLs
        BlockPublicPolicy: true  # Blocks public policies
        RestrictPublicBuckets: true  # Restricts public buckets
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionMethod: AES256  # Enables AES256 encryption
      LoggingConfiguration:
        DestinationBucketName: logging-bucket-name  # Logging destination bucket
        LogFilePrefix: logs/  

