AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for creating a secure S3 bucket with versioning, encryption, and logging enabled.

Resources:
  SecureIACBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: secureiac
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: "logs/"

  LoggingBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "secureiac-logging-bucket"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref SecureIACBucket
    Export:
      Name: !Sub "${AWS::StackName}-Bucket"
