AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AuditLoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: secureiac-audit-logs
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Enabled

  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: secureiac-logs
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref AuditLoggingBucket
        LogFilePrefix: "audit-logs/"

  SecureIACBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: secureiac
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: "logs/"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

Outputs:
  SecureIACBucketName:
    Description: "Name of the secure S3 bucket"
    Value: !Ref SecureIACBucket

  LoggingBucketName:
    Description: "Name of the logging S3 bucket"
    Value: !Ref LoggingBucket

  AuditLoggingBucketName:
    Description: "Name of the audit logging S3 bucket"
    Value: !Ref AuditLoggingBucket
