Resources:
  SecureIACBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: secureiac
      VersioningConfiguration:
        Status: Enabled  # Enable versioning for the bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true  # Block public ACLs
        IgnorePublicAcls: true  # Ignore public ACLs
        BlockPublicPolicy: true  # Block public policies
        RestrictPublicBuckets: true  # Restrict public buckets
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionMethod: AES256  # Enable server-side encryption
      LoggingConfiguration:
        DestinationBucketName: logging-bucket-name  # Replace with the actual logging bucket
        LogFilePrefix: logs/  # Define a prefix for the log files
