name: Deploy S3 Buckets with Security Checks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read   # Required for accessing repository content

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::235494823972:role/S3bucket-IAC
        aws-region: ap-south-1

    - name: Install Checkov (latest version)
      run: |
        pip install -U checkov

    - name: Run Checkov to enforce security best practices
      run: |
        checkov -f Secure-S3.yml --quiet

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation create-stack \
          --stack-name SecureIACStack \
          --template-file Secure-S3.yml \
          --region ap-south-1

    - name: Verify S3 Bucket Exists
      run: |
        echo "Checking if S3 bucket 'secureiac' exists..."
        until aws s3 ls "s3://secureiac" 2>/dev/null; do
          echo "Waiting for S3 bucket secureiac to be created..."
          sleep 5
        done
        echo "S3 bucket secureiac is ready."

    - name: Upload index.html to S3 bucket
      run: |
        aws s3 cp index.html s3://secureiac/index.html
