on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read   # Required for accessing repository content

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::235494823972:role/S3bucket-IAC
        aws-region: ap-south-1

    - name: Install Checkov (latest version)
      run: |
        pip install -U checkov

    - name: Run Checkov to enforce security best practices
      run: |
        checkov -f Secure-S3.yml --quiet || { echo 'Checkov scan failed'; exit 1; }

    - name: Validate CloudFormation Template
      run: |
        aws cloudformation validate-template --template-body file://Secure-S3.yml
        if [ $? -ne 0 ]; then
          echo "CloudFormation template validation failed"
          exit 1
        fi

    - name: Delete Stack if in REVIEW_IN_PROGRESS
      run: |
        STATUS=$(aws cloudformation describe-stacks --stack-name SecureIACStack --query 'Stacks[0].StackStatus' --output text || echo "NOT_FOUND")
        echo "Current stack status: $STATUS"
        if [[ "$STATUS" == "REVIEW_IN_PROGRESS" ]]; then
          echo "Stack is stuck in REVIEW_IN_PROGRESS. Deleting..."
          aws cloudformation delete-stack --stack-name SecureIACStack
          aws cloudformation wait stack-delete-complete --stack-name SecureIACStack
        fi

    - name: Deploy CloudFormation Stack
      run: |
        echo "Deploying CloudFormation stack..."
        aws cloudformation deploy \
          --stack-name SecureIACStack \
          --template-file Secure-S3.yml \
          --capabilities CAPABILITY_NAMED_IAM \
          --no-fail-on-empty-changeset \
          --region ap-south-1 || { echo 'CloudFormation deploy failed'; exit 1; }

    - name: Verify S3 Bucket Exists
      run: |
        echo "Checking if S3 bucket 'secureiac' exists..."
        until aws s3 ls "s3://secureiac" 2>/dev/null; do
          echo "Waiting for S3 bucket secureiac to be created..."
          sleep 5
        done
        echo "S3 bucket secureiac is ready."

    - name: Upload index.html to S3 bucket
      run: |
        echo "Uploading index.html to S3 bucket..."
        aws s3 cp index.html s3://secureiac/index.html || { echo 'S3 upload failed'; exit 1; }
