name: Create S3 Bucket and Upload index.html

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  
      contents: read   

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::235494823972:role/S3bucket-IAC
        aws-region: ap-south-1

    - name: Install Kics
      run: |
        curl -sSL https://github.com/Checkmarx/kics/releases/download/v1.8.1/kics-linux-amd64.tar.gz | tar -xz
        sudo mv kics /usr/local/bin/

    - name: Run Kics to scan CloudFormation template
      run: |
        kics scan --path S3_Bucket_Creation.yml --preset checkov

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file S3_Bucket_Creation.yml \
          --stack-name SecureIACStack \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Upload index.html to S3 bucket
      run: |
        aws s3 cp index.html s3://secureiac/index.html
