name: Deploy S3 Buckets with Security Checks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read   # Required for accessing repository content

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::235494823972:role/S3bucket-IAC
        aws-region: ap-south-1

    - name: Install Checkov (latest version)
      run: |
        pip install -U checkov

    - name: Run Checkov to enforce security best practices
      run: |
        checkov -f Secure-S3.yml --quiet

    - name: Validate CloudFormation Template
      run: |
        aws cloudformation validate-template --template-body file://Secure-S3.yml

    - name: Delete Stack if in REVIEW_IN_PROGRESS
      run: |
        STATUS=$(aws cloudformation describe-stacks --stack-name SecureIACStack --query 'Stacks[0].StackStatus' --output text || echo "NOT_FOUND")
        if [[ "$STATUS" == "REVIEW_IN_PROGRESS" ]]; then
          echo "Stack is stuck in REVIEW_IN_PROGRESS. Deleting..."
          aws cloudformation delete-stack --stack-name SecureIACStack
          aws cloudformation wait stack-delete-complete --stack-name SecureIACStack
        fi

    - name: Create Change Set
      run: |
        aws cloudformation create-change-set \
          --stack-name SecureIACStack \
          --template-body file://Secure-S3.yml \
          --capabilities CAPABILITY_NAMED_IAM \
          --change-set-name SecureIACChangeSet || echo "No changes detected."

    - name: Execute Change Set
      run: |
        aws cloudformation execute-change-set --change-set-name SecureIACChangeSet --stack-name SecureIACStack || echo "Skipping execution."

    - name: Upload index.html to S3 bucket
      run: |
        aws s3 cp index.html s3://secureiac/index.html
